### ISSUE TITLE
Tibetan Lakes tutorial

### ISSUE THREAD

**Issue by gareth-j** [4DModeller/fdmr#105]
We need to get a finished Tibetan lakes tutorial together. At the moment I've just used some of the data to create a `data.frame` to pass into the mesh builder Shiny app.

**Comment by gareth-j** [comment]
No, not with anything big on, have you got a branch for a tutorial?

**Comment by mnky9800n** [comment]
this ineeds to be merged from https://github.com/4DModeller/fdmr/tree/tblakes-tutorial
