### ISSUE TITLE
hydropower tutorial uses rgdal

### ISSUE THREAD

**Issue by mnky9800n** [4DModeller/fdmr#134]
rgdal will be deprecated in October 2023 and removed from everything. Currently hydro tutorial directly calls rgdal to import data. 

Example:

```norway_polygon <- rgdal::readOGR(norway_polygon_path)```

This should be substituted for somethign not rgdal.

**Comment by gareth-j** [comment]
Related to #102

**Comment by gareth-j** [comment]
Done.
