### ISSUE TITLE
hydro tutorial should use new mesh mapper

### ISSUE THREAD

**Issue by mnky9800n** [4DModeller/fdmr#135]
Currently the hydro tutorial uses the built in plotting function to plot the mesh like so:

![image](https://github.com/4DModeller/fdmr/assets/942355/e2604b17-8c6d-462e-8bff-f93a9258cd4a)

However we should have it use the more useful fdmr tools to map it like it does in the meshbuilder app.

**Comment by mnky9800n** [comment]
something like this:

https://github.com/4DModeller/fdmr/blob/main/R/meshing.R

**Comment by gareth-j** [comment]
Closed by #162
