### ISSUE TITLE
should we deprecate mapping.rmd?

### ISSUE THREAD

**Issue by mnky9800n** [4DModeller/fdmr#136]
There are a bunch of different mapping options and this just kind of adds on to the mess. We kind of moved away from making a simple map making tool and that became to mesh mapping tool. So does this tutorial do anything anymore?

**Comment by mnky9800n** [comment]
We could also refactor this to be a one stop shop for all the different ways we are able to build maps within fdmr.

**Comment by gareth-j** [comment]
Remove this and the mapping Shiny app.

**Comment by gareth-j** [comment]
Done with #166
