### ISSUE TITLE
end to end tutorial mapping issues

### ISSUE THREAD

**Issue by mnky9800n** [4DModeller/fdmr#139]
I'm not sure but I don' think this is what the map should look like at the end:

<img width="981" alt="image" src="https://github.com/4DModeller/fdmr/assets/942355/5ca6a809-4466-4ee1-9f8f-d43b87619f0c">

it seems like its not exactly right.

**Comment by XueqingYin** [comment]
This is because the simulated polygons are rectangular and overlapping. I've now fixed it by simulating the data with Bristol as the study region.

 Xueqing

**Comment by mnky9800n** [comment]
Can you please create a pull request for your fix @XueqingYin
