### ISSUE TITLE
mesh builder needs a checkbox to create a boundary layer

### ISSUE THREAD

**Issue by mnky9800n** [4DModeller/fdmr#148]
quite often you want a low resolution layer between the observation area and teh edge of the modeling mesh. this is to prevent numerical issues.

if there was a checkbox to "add a boundary layer" or something like that, that would be great since it is super common but currently doesn't exist in the mesh builder app.

**Comment by gareth-j** [comment]
Is this by passing objects to the `boundary` argument of the meshing function?

**Comment by XueqingYin** [comment]
Hi @mnky9800n , if I'm understanding you correctly, are you referring to the external extension that's used to avoid numerical issues? If so, I think it already exists in the current mesh builder application through the "offset" parameter. In the mesh builder, users need to input two values for both "offset" and "max.edge," one value for the inner extension and one for the outer extension. So I'm not quite sure if we need to add a checkbox for the option to "include a boundary layer"...
