### ISSUE TITLE
priors app should rename exposure parameter

### ISSUE THREAD

**Issue by mnky9800n** [4DModeller/fdmr#152]
The exposure parameter is the name of the time index. This is the regular name from statistics, although i think it is not so interesting a name for newcomers. Can we rename it to one of the following:

Exposure (time variable)
Time Variable (Exposure)
etc.

something like that.

**Comment by gareth-j** [comment]
Done with bd9101f8f6096c9984f0e26d050764596b65ae20

**Comment by gareth-j** [comment]
Done with #147
