### ISSUE TITLE
Change the y and x-axis labels in the `plot_priors_boxplot()` and 'plot_priors_density()' function

### ISSUE THREAD

**Issue by XueqingYin** [4DModeller/fdmr#184]
The label on the y-axis in the ```plot_priors_boxplot()``` function needs to be changed as "Fitted values", because 'Rate estimates' is only suitable for the COVID tutorials

**Comment by XueqingYin** [comment]
Also need to change the x-axis label "Rate estimates" in the ```plot_priors_density()``` function into  "Fitted values".

**Comment by gareth-j** [comment]
Done with #185
