### ISSUE TITLE
Minor coding or tutorial issues

### ISSUE THREAD

**Issue by XueqingYin** [4DModeller/fdmr#190]
I went through each of the tutorials and test the functions with the tutorial data.  I found a few minor issues to fix.  Here is a summary of them:

1. The comma in ```family_control_str <- "list(link = 'log')," ``` duplicates the last comma in the model code output ```control.family = ", family_control_str, ",``` in shiny_priors.R
2. The use of the ```fdmr::model_viewer()``` function is not demonstrated in the Poisson simulation tutorial.
3. The use of the ```fdmr::model_viewer()``` function is not demonstrated in the Gaussian simulation tutorial.
4. The argument ```time_variable="week"``` in the ```model_builder()``` function is missing in priors.Rmd
5. Having a `stats::` prefix before the offset term in the MCMC model formula in covid_mcmc.Rmd leads to weird results. So `stats::` should be deleted. 
6. Remove the question ("HOW MUCH IS ENOUGH") in the line 227 in covid.Rmd

I will fix them and pull a request.

**Comment by aabelean** [comment]
Not an issue per se, but could the line 227 in covid.Rmd be changed to specify or remove the question ('HOW MUCH IS ENOUGH?')?

**Comment by XueqingYin** [comment]
Good point, thanks @aabelean. I will change that in my pull request #194

**Comment by gareth-j** [comment]
Closes by #194
