### ISSUE TITLE
Cannot retrieve the tibetan_lakes data

### ISSUE THREAD

**Issue by XueqingYin** [4DModeller/fdmr#191]
In meshbuilder.Rmd, when I use ```fdmr::retrieve_tutorial_data(dataset = "tibetan_lakes")``` to download the tibetan_lakes data, I got the following error

![tibetanlake_data](https://github.com/4DModeller/fdmr/assets/83759494/7f20dfda-ded1-4827-b9f0-c02e8dc7034c)

@gareth-j @mnky9800n , have you ever come across this error? I feel it's strange because the error doesn't seem to exist in the Mesh building tutorial on the website.

**Comment by mnky9800n** [comment]
This also happens for me as well. but if you look at the dataset repo its there:

https://github.com/4DModeller/fdmr_data

@gareth-j do you know what is going on?

**Comment by mnky9800n** [comment]
but also, this data should be updated. @gareth-j i shared with you on slack.

**Comment by gareth-j** [comment]
@XueqingYin does this still happen if you do `fdmr::retrieve_tutorial_data(dataset = "tibetan_lakes", force_update = TRUE)`?

**Comment by XueqingYin** [comment]
No. The data can be retrieved now with force_update = TRUE

**Comment by gareth-j** [comment]
OK great, I'll close this.
