### ISSUE TITLE
the website doesn't build when you push to main

### ISSUE THREAD

**Issue by mnky9800n** [4DModeller/fdmr#2]
No reason why. I changed the title of the Readme to see what would happen and it doesn't update. The action fails:

https://github.com/4DModeller/fdmr/actions/runs/4763742608

**Comment by jlbamber** [comment]
Hmm, that’s not so useful…

From: John Aiken ***@***.***>
Sent: 21 April 2023 12:19
To: 4DModeller/fdmr ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [4DModeller/fdmr] the website doesn't build when you push to main (Issue #2)


No reason why. I changed the title of the Readme to see what would happen and it doesn't update. The action fails:

https://github.com/4DModeller/fdmr/actions/runs/4763742608
