### ISSUE TITLE
the time_variable attribute for model builder will accept non-existent columns in the dataframe and allow the app to load

### ISSUE THREAD

**Issue by mnky9800n** [4DModeller/fdmr#200]
If you create an otherwise working dataset, but specify a time variable that doesn't exist, the app will still load even though this time variable does not exist in the data set:

for example, using the tibetan lakes dataset you can load in the data and the mesh and the `time_variable` should be "year" however it is "week". The app will still load. The expected behavior i would think is the app fails with the error message that the `time_variable` doesn't exist in the data set.
```
sp::coordinates(data) <- c("centroid_lon", "centroid_lat")
fdmr::model_builder(spatial_data = data, measurement_data = data, mesh = mesh, time_variable = "week")
```

**Comment by gareth-j** [comment]
Closed with #216
