### ISSUE TITLE
tibetan_lakes dataset cannot be downloaded from fdmr

### ISSUE THREAD

**Issue by icetianli** [4DModeller/fdmr#203]
I try to download the tibetan_lakes datasets from fdmr using the following command : 
`fdmr::retrieve_tutorial_data(dataset = "tibetan_lakes")`

It will show the following error:
`Error: archive_extract.cpp:166 archive_read_next_header(): Ignoring malformed pax extended attribute`

It seems this file is broken.

**Comment by aabelean** [comment]
I get the same error on atlantis, but on Windows it even fails to find the dataset as in issue #191.

**Comment by mnky9800n** [comment]
Hi, I think @Gareth Jones ***@***.***> needs to update the
data set in the other repo.

This is an ongoing issue because we've had this problem with this data set
everywhere.

**Comment by icetianli** [comment]
Just found the same problem with downloading the `priors `dataset using `fdmr::retrieve_tutorial_data(dataset = "priors")`.

**Comment by aabelean** [comment]
Hmm, it did work for me on atlantis at least. I did receive a warning `/bin/gtar: Ignoring unknown extended header keyword LIBARCHIVE.xattr.com.apple.provenance`, which did not appear elsewhere.

**Comment by mnky9800n** [comment]
this seems to be an ongoing issue everywhere as i am able to do this as well.

```
tl <- fdmr::retrieve_tutorial_data(dataset="tibetan_lakes")

Tutorial data extracted to  /Users/johnaiken/fdmr/tutorial_data/tibetan_lakes 
Error in exists(cacheKey, where = .rs.WorkingDataEnv, inherits = FALSE) : 
  invalid first argument
```

what branch are you guys on? devel?

**Comment by icetianli** [comment]
Thanks for the updates @aabelean, I just reinstalled fdmr and I can now download `tibetan_lakes`, `priors `and `covid `datasets.  now.

**Comment by mnky9800n** [comment]
@aabelean can you test to see if you are on the correct branch? maybe its that its an older version or the wrong branch, if you are not creating a new feature you should be on devel or main. (devel will have new features from `0.1.0` but may also be less stable).

if updating works for you @aabelean just say here and close the issue.

**Comment by aabelean** [comment]
Yes, works for `main` branch if updated.
