### ISSUE TITLE
the clear button leaves the f() function on the model builder app

### ISSUE THREAD

**Issue by mnky9800n** [4DModeller/fdmr#204]
if you have lots of variables like this

<img width="897" alt="image" src="https://github.com/4DModeller/fdmr/assets/942355/4e7794d4-5638-4e56-8740-64b6d5ae07b8">

then click the clear button you get this

<img width="897" alt="image" src="https://github.com/4DModeller/fdmr/assets/942355/1df617b4-32ce-4182-b9cb-2de68b8241a3">

my expectation would be that the clear button would also remove the f() check box.

**Comment by mnky9800n** [comment]
those screen shots are incorrect, these are correct:

first
<img width="897" alt="image" src="https://github.com/4DModeller/fdmr/assets/942355/976e957e-7b8e-487c-9be3-33e6aa7d5674">

second

<img width="897" alt="image" src="https://github.com/4DModeller/fdmr/assets/942355/f67dd550-4484-488b-b25d-741ddfd26ef6">

**Comment by icetianli** [comment]
Also when running the model builder app, after clicking the `run` button, have you ever encountered the following error from `inla`:
```
This is INLA_23.10.19-1 built 2023-10-19 08:26:30 UTC.
 - See [www.r-inla.org/contact-us](http://www.r-inla.org/contact-us) for how to get help.
 - List available models/likelihoods/etc with inla.list.models()
 - Use inla.doc(<NAME>) to access documentation
Warning in iinla(model = info[["model"]], lhoods = info[["lhoods"]], options = info[["options"]]) :
  iinla: Problem in inla: Error in inla.core.safe(formula = formula, family = family, contrasts = contrasts,  :
  *** Failed to get good enough initial values. Maybe it is due to something else.
iinla: Problem in inla: 1: workRSOCK()
```
I can't get any results, should `inla` be reinstalled in this case?

**Comment by gareth-j** [comment]
Done with #215
