### ISSUE TITLE
if map values have long tails on the distribution the heatmap looks like its the same everywhere

### ISSUE THREAD

**Issue by mnky9800n** [4DModeller/fdmr#212]
If you make a map of the predicted output and it has long tails (e.g., in the model viewer or the priors app), the output map looks like all the values are the same but they are not.

<img width="832" alt="image" src="https://github.com/4DModeller/fdmr/assets/942355/ca3fcde3-0cdd-4d8b-9d01-dc0808078bd7">

here is another exmaple with a diverging colormap

<img width="832" alt="image" src="https://github.com/4DModeller/fdmr/assets/942355/26824d40-ca23-4c4b-8639-e462f3ea1dc1">

and if we look here we can see there are clearly a lot of zero values (this is because the predicted variable is zscored) but there is a long tail on either side (gaussian distributed).

![image](https://github.com/4DModeller/fdmr/assets/942355/ecb7df0c-0772-43db-a83a-4d9ffee96b31)

so we need better handling of the variation in this data so it doesnt appear like there isnt any. my suggestion is that we simply allow the user to choose the max and min of the color map through whatever is simplest possible at the moment.

**Comment by gareth-j** [comment]
Done with #218
