### ISSUE TITLE
Shiny apps never generate code associated with input variable names

### ISSUE THREAD

**Issue by mnky9800n** [4DModeller/fdmr#217]
When you use an app to create codes it doesn't use the input variable name it uses the function attribute that accepts the input variable. This becomes counter intuitive later when you copy and paste because a newcomer may not realise that they need to change anything since there's nothing stated that you should.

I suggest either

1. Change the code generator so it uses the actual variable name
2. Add inline comments in the generated code that tells the user where they may need to change the variable name in the generated code

I guess 2 is easier to do before the Hackathon.

**Comment by gareth-j** [comment]
Sorry I don't really get what you mean, can you give an example?

**Comment by mnky9800n** [comment]
for example, in the tibetan lakes tutorial see here: https://github.com/4DModeller/fdmr/blob/433eab5bdc3304bcf8372b0adf8fcdca1da27309/vignettes/tibetan-lakes.Rmd#L114

the output code is:

```
mesh <- fmesher::fm_mesh_2d_inla(loc = location_data,
          max.edge = c(0.1, 0.3),
          cutoff = 0.2,
          offset=c(0.2, 0.7))
```

but to make the code work in the R file you need to change it to:

```
mesh <- fmesher::fm_mesh_2d_inla(loc = data[, c("centroid_lon", "centroid_lat")],
          max.edge = c(0.1, 0.3),
          cutoff = 0.2,
          offset=c(0.2, 0.7))
```

because the shiny app doesn't reference the data for `loc` directly, it has the the placeholder `location_data`.

my recommendation is to fix this simply put in the comment:

```
mesh <- fmesher::fm_mesh_2d_inla(loc = location_data, # CHANGE TO YOUR VARIABLE
...
```

or something like that. later we can make it more responsive if we want.
