### ISSUE TITLE
Invalid crs when building mesh using era5 data in hydrology example

### ISSUE THREAD

**Issue by icetianli** [4DModeller/fdmr#220]
When building 2d mesh following the code provided in the [hydrology tutorial](https://4dmodeller.github.io/fdmr/articles/hydro.html), it will show the following error:

```
> xy <- sp::coordinates(era5_precip_cropped)
> xy <- xy[seq(1, nrow(xy), by = 2), ]
> 
> colnames(xy) <- c("LONG", "LAT")
> 
> mesh <- fmesher::fm_mesh_2d_inla(loc = xy, max.edge = c(xres * 1, xres * 100), cutoff = 75, crs=crs)

Error in st_crs.character(x, ...) : 
  invalid crs: 
GEODCRS["unknown",DATUM["unknown",ELLIPSOID["unknown",1,0,LENGTHUNIT["metre",1,ID["EPSG",9001]]]],
PRIMEM["Reference meridian",0,ANGLEUNIT["degree",0.0174532925199433,ID["EPSG",9122]]],
CS[Cartesian,3],AXIS["(X)",geocentricX,ORDER[1],
LENGTHUNIT["metre",1,ID["EPSG",9001]]],
AXIS["(Y)",geocentricY,ORDER[2],
LENGTHUNIT["metre",1,ID["EPSG",9001]]],AXIS["(Z)",geocentricZ,ORDER[3],
LENGTHUNIT["metre",1,ID["EPSG",9001]]]]
```
Package version:
```
R 4.2.0
fdmr 0.1.0
INLA 23.10.19-1
```

**Comment by aabelean** [comment]
Can reproduce this with `INLA 23.10.25` on Linux for `R 4.2.0` (`sf 1.0-14` as the function `st_crs` is associated with `sf`). Do you also get the same error in mesh_builder Shiny app, for instance, for tutorial `simulation_gaussian_data`?

**Comment by icetianli** [comment]
Yea just ran `simulation_gaussian_data` and got the same error in the shiny app when creating mesh.

**Comment by gareth-j** [comment]
What version of `fmesher` are you guys using? Does it work if you do `crs <- fmesher::fm_crs("+proj=utm +zone=32")` ?

**Comment by aabelean** [comment]
I have `fmesher 0.1.3`. Will check if your suggestion works.

**Comment by icetianli** [comment]
Version `fmesher 0.1.3` as well, `crs <- fmesher::fm_crs("+proj=utm +zone=32") ` has the same error.

**Comment by aabelean** [comment]
Just as @icetianli said, fmesher gives the same error with this fix.

**Comment by gareth-j** [comment]
Does it work if you do `sp::CRS("+proj=utm +zone=32")` ?

**Comment by aabelean** [comment]
Nope, no difference. There is another bug in the same cell: could you replace line 225 (`plot_mesh(mesh)`) with (`fdmr::plot_mesh(mesh)`)?

**Comment by aabelean** [comment]
Main

**Comment by gareth-j** [comment]
> Main

Can you try it on devel? And do a `load_all` before you run the tutorial?

**Comment by gareth-j** [comment]
Also can you update `fmesher` to `1.4.0`?

**Comment by aabelean** [comment]
Sure, @gareth-j.

**Comment by mnky9800n** [comment]
I have been unable to replicate this issue on either

* mac os x sonoma m1
* windows 10

**Comment by gareth-j** [comment]
I think this may be an issue on Linux systems where the user has done a binary install of INLA and there's mismatch in what the versions of packages are passing between themselves (INLA, inlabru and fmesher) that's causing that issue. I've tried to reproduce this on a fresh Ubuntu VM and can't.
