### ISSUE TITLE
Dealing with wrapping longitude boundary

### ISSUE THREAD

**Issue by aabelean** [4DModeller/fdmr#225]
I tested the original (legacy) meshes from GlobalMass and plotted them with `plot_map()`. Ignoring the fact that the meshes contain a lot of isolated triangles, I found that this map distorts the triangles that span the longitude wrapping boundary (180/-180 meridian) and makes them appear across the map like shown in the pictures below.
![image](https://github.com/4DModeller/fdmr/assets/57137242/2dd16770-e2ab-41af-8e17-00a1aa37729c)
Zoom in close to Wrangel Island (from each side):
![image](https://github.com/4DModeller/fdmr/assets/57137242/22baeba1-35a3-4042-999d-ffc486c7667d)
![image](https://github.com/4DModeller/fdmr/assets/57137242/67dd3104-d9ca-41cf-8de5-77a0bb8a2d85)

We need to find a way to either mask these triangles or allow splitting the triangle on each side.

**Comment by mnky9800n** [comment]
@aabelean can you look at the leaflet documentation and see if there is any meniton of mapping across the longitude divide?

**Comment by aabelean** [comment]
Yes, @mnky9800n there are multiple mentions of this issue. This was first raised in [2011](https://github.com/Leaflet/Leaflet/issues/82#issuecomment-1260488) with the first release of `leaflet`. Unfortunately, base `leaflet` did not implement the fix, but it is available through the [Leaflet.Antimeridian plugin](https://github.com/briannaAndCo/Leaflet.Antimeridian). However, there is an [open issue in rstudio/leaflet from 2018](https://github.com/rstudio/leaflet/issues/553) to incorporate this as either as base or additional functionality, so we can't really use it in R.

The current workaround (from said 2011, in absence of support for Leaflet.Antimeridian) is to allow these objects to exceed the 180 degree boundary by adding 360 to the negative values. This cannot be done indiscriminately as we would just transfer the problem to Greenwich meridian. My suggestion is to check LONG coordinates of each polygon: if there is a mismatch in sign with other coordinates, we just add 360 to it.
For `plot_mesh` it is a bit more complicated. If we work, for instance, in Beringia/Chukotka, we get triangle vertices that are shared by triangles that cross the anti-meridian and also those that don't. We cannot just change the coordinates of those points. Instead, we should add new vertices with coordinates transformed. I will do more rigorous testing with this before pushing anything as I think there is a great risk of breaking something.
It can be an issue for Shiny app `mesh_builder` too, but I think the map is rendered differently in Shiny apps, so might need a different fix. I will check it as well.
