### ISSUE TITLE
model viewer plots should have explanations

### ISSUE THREAD

**Issue by mnky9800n** [4DModeller/fdmr#232]
The model viewer app has a lot of interesting plots and maps however it is missing explanations for each. While an explanation for the actual results is beyond the scope of 4d-modeller, it would be realy nice if there was an explanation for each type of plot. For example, what does the AR(1) plot tell you, what does the predicted mean field map tell you? how is it calculated? is there some reference for each? This would be instructive for users.

**Comment by XueqingYin** [comment]
Hi, here are some explanations for the plots in the modelbuilder app. 

Explanations for Plot output:
The Range plot provides a plot of the posterior distribution of the spatial range parameter ρ, the distance at which the correlation between two points is approximately 0.

The Stdev plot provides a plot of the posterior distribution of the marginal standard deviation σ of the spatial field. 

The  AR(1) plot provides a plot of the posterior distribution of the temporal autocorrelation α. A value close to 1 indicates strong positive temporal dependence, a value  of 0 indicates independence across time, and a value close to -1 indicates strong negative temporal dependence.

The Boxplot displays the predicted (or fitted) values across the observed locations and time points,  showing how the predictions are distributed.

The Density plot displays the density curve of the predicted (or fitted) values across the observed locations and time points. 

The DIC plot displays the Deviance Information Criterion (DIC) value for the model. DIC is a model selection criterion, with lower values indicating better model fit.

Explanations for Map:
The plot of predicted mean fields maps the predicted values across a number of grid locations that cover the study region. It helps to identify areas with high predictions and those with low predictions. The predicted values at observed locations can be obtained by using the syntax ```model_output$summary.fitted.values$mean[1:nrow(observed_data)]```. The predicted values at the grid locations are calculated using the method described in the priors tutorial https://4dmodeller.github.io/fdmr/articles/priors.html.

The plot of random effect fields maps the random effect values (the f() values) across a number of grid locations that cover the study region. The random effect values at the mesh nodes and time points can be obtained by using the syntax``` model_output$summary.random$f$mean```.

**Comment by gareth-j** [comment]
Add to the help tab in the model viewer.
