### ISSUE TITLE
namespace ‘INLA’ is imported by ‘fdmr’ so cannot be unloaded

### ISSUE THREAD

**Issue by Elchin** [4DModeller/fdmr#244]
in COVID tutorial, after executing the first line
```
> library(INLA)
Error in value[[3L]](cond) : 
  Package ‘INLA’ version 23.10.28 cannot be unloaded:
 Error in unloadNamespace(package) : namespace ‘INLA’ is imported by ‘fdmr’ so cannot be unloaded
```

**User Environment (please complete the following information):**
 - OS: [e.g. macOS, Windows, Ubuntu]
 - R version 4.3.1 (2023-06-16)
 - (https://github.com/4DModeller/fdmr/releases/tag/0.1.1)

**Comment by komoseid** [comment]
I hd the same error and reran this with success
```
install.packages("devtools")
library(devtools)
devtools::install_github("4DModeller/fdmr")
```

**Comment by mnky9800n** [comment]
this seems to have solved the problem.
