### ISSUE TITLE
`future` missing from `DESCRIPTION`

### ISSUE THREAD

**Issue by gareth-j** [4DModeller/fdmr#246]
**Describe the bug**
The `future` package isn't installed when we 

**Expected behavior**
Install `future`

**To Reproduce**
Install `fdmr` from GitHub and try the modelbuilder tutorial.

**User Environment (please complete the following information):**
 - OS: Many
 - Version of R
 - Version of fdmr you are using

**Comment by komoseid** [comment]
same with package: bsicons

**Comment by KateHeerema** [comment]
It then also requested `bsicons` after `future` is installed.

**Comment by gareth-j** [comment]
Done with #263
