### ISSUE TITLE
UTM issue with mesh_builder()

### ISSUE THREAD

**Issue by mmazzolini** [4DModeller/fdmr#248]
from the Snow group:

we found it problematic to make the mesh_builder work with UTM coordinates. the fmesher function works though.

We also want to add the coordinates of observations.
plot_mesh() works with just the mesh.
when we add the spatial_coordinates this crashes. still we're utm coordinates.

The data can be found at "desireetreichler/fdmr/tree/snow/vignettes/data/Bayelva_snow.nc.

We are now working with data variables Ys, Xs, DS. see the tutorial "desireetreichler/fdmr/tree/snow/vignettes/snow.RMD

Thanks.

**Comment by gareth-j** [comment]
If I try and build the mesh using `fm_mesh_2d_inla` I get the error:

```r
Rcpp_interface.cc(373)	Points not in the plane or on a sphere, and triangulation empty.
meshc.cc(1308)	NOT IMPLEMENTED: bool fmesh::MeshC::CET(int, double)
Rcpp_interface.cc(373)	Points not in the plane or on a sphere, and triangulation empty.
meshc.cc(1308)	NOT IMPLEMENTED: bool fmesh::MeshC::CET(int, double)
```

**Comment by finnlindgren** [comment]
What's the `head()` and `str()` output for the data you're providing to the `loc` argument of `fm_mesh_2d_inla()`?
