### ISSUE TITLE
Object "DICs" not found - How to choose a model tutorial

### ISSUE THREAD

**Issue by MargotK25** [4DModeller/fdmr#249]
**Describe the bug**
Error object "DICs" not found when running the last line of code in the "How to choose a model" tutorial: 
`plot(DICs)`

**Expected behavior**
Object "DICs" should be defined before it can be used in the plot function. 

**User Environment (please complete the following information):**
 - OS: Windows
 - Version of R: 4.3.1
 - Version of fdmr you are using: 0.1.1

**Comment by gareth-j** [comment]
Remove the `Comparing the output` section of the tutorial.
