### ISSUE TITLE
User friendly data loading functions

### ISSUE THREAD

**Issue by gareth-j** [4DModeller/fdmr#253]
User friendly functions

We could do a quick schema check when we read them in and then give the user helpful information so they can edit their data to make it more easily readable?

`fdmr::load_netcdf` - could we have a function that's
`fdmr::load_csv` 

## Data schema tutorial

We could create a tutorial on loading and cleaning (REAL WORLD) data from Copernicus or SIOS and getting it into a format that's read to use in the mesh builder and other Shiny tools.

**Comment by mnky9800n** [comment]
i think this is going in the right deirection but i think the tutorial is the best idea. i got a lot of questions in the hackathon like "what do i do if i want to load my own data and not the data from the tutorial?"

**Comment by mnky9800n** [comment]
i do not think we should make loader functions because then we will have to support loader functions and all they will do is wrap some other library that loads netcdf, csv, etc.
