### ISSUE TITLE
mesh doesnt plot when you knit an r-markdown but does plot when you run it in rstudio

### ISSUE THREAD

**Issue by mnky9800n** [4DModeller/fdmr#307]
rstudio

<img width="1291" alt="image" src="https://github.com/4DModeller/fdmr/assets/942355/26781ef7-a17d-4202-a97b-709972714298">

knitted r-markdown

<img width="1291" alt="image" src="https://github.com/4DModeller/fdmr/assets/942355/3541d3d2-e4d5-4fd7-85bd-d20967e88b7f">

**Comment by aabelean** [comment]
Can we close it? I can knit it after the fix #306.
