### ISSUE TITLE
data loading functions

### ISSUE THREAD

**Issue by mnky9800n** [4DModeller/fdmr#31]
I really dislike the data loading functions. It obfuscates the entire process of loading data, often which is not an easy task given the various formats (geojson, netcdf, data from data APIs, etc.). In some cases, it has not been a small amount of work to put together several different tutorials to figure out how to download and load the data in the tutorial. Therefore having the actual process of grabbing the data could be quite useful to users if they need the same data. I do not think we can have a loading function for every kind of data format we could anticipate. This really strikes me as premature optimisation. I think we should just have the raw codes in the tutorials and jettison all of these wrapper functions.

**Comment by gareth-j** [comment]
I think this has been covered by Xueqing's data reading tutorial from #63
