### ISSUE TITLE
can we make some updates to the home page website

### ISSUE THREAD

**Issue by mnky9800n** [4DModeller/fdmr#5]
Hi Can we add the following:

* links to github profile for each of the authors (if exists)
* 4d-modeller logo to top
* favicon for the website using only the grid part of the logo
* i changed the title to say 21st century but it shouldn't actually say that, i was being somewhat facetious
*

**Comment by gareth-j** [comment]
OK this is almost done.

I'm aware that the size of the logo is tiny, I'll look into this that's why this issue and the PR are parked at the moment.

**Comment by gareth-j** [comment]
Done with #10
