### ISSUE TITLE
priors + modeling shiny app

### ISSUE THREAD

**Issue by mnky9800n** [4DModeller/fdmr#54]
As discussed in the milestone meeting, we need a way to visualize priors and model impacts on the predictive ability of the model.

In the below diagram i have sketched out a shiny app interface that will let us do that.

* at the top there is a slider bar to change the prior value for the spatial wavelength of the prior
* below is a list of features based on the input data column headers that can be used to construct the fit equation
* below the list of features is the constructed equation
* to the right is the visualization. in this case i assume that the visualization should be the collected outcome variable (y) that has been histogrammed in some way that is agnostic to the data. Then a kernel density estimate of the model predicted variables (that is, basically, a continuous histogram) is plotted on top to show the model.
* There could also be "run model" button at the bottom to match the mesh builder app, that way it doesn't need to auto update

![image](https://github.com/4DModeller/fdmr/assets/942355/61c0dfa7-95f7-4e23-ab30-1d1302fca5f1)

**Comment by gareth-j** [comment]
Worked on in #57
