### ISSUE TITLE
Shiny app - logging?

### ISSUE THREAD

**Issue by gareth-j** [4DModeller/fdmr#76]
Would logging model output and prior sets to file be helpful?

**Comment by XueqingYin** [comment]
Hi @gareth-j, 

I think logging both the model output summary (obtained from summary(inlabru_model)) and the prior sets (maybe in the form of a data frame) would help users with quickly examining and comparing parameter values and model performance across models with different priors. 

Xueqing

**Comment by gareth-j** [comment]
OK great, I'll get a PR started for that.
