### ISSUE TITLE
website still does not point to repo correctly

### ISSUE THREAD

**Issue by mnky9800n** [4DModeller/fdmr#8]
The website does not point to the repo, it populates the URLs with /NA/NA/NA instead. I guess this is an roxygen2 issue?

see the url in the lower left which leads to a 404.

<img width="1624" alt="image" src="https://user-images.githubusercontent.com/942355/234502879-01631154-0449-4fd9-b119-2f033bfe193d.png">

**Comment by gareth-j** [comment]
OK this has been fixed with d0caa2c, weird that that fixed it but hey.
