### ISSUE TITLE
webpage root domain goes to 404

### ISSUE THREAD

**Issue by mnky9800n** [4DModeller/fdmr#94]
if you go to https://4dmodeller.github.io/ it goes to a 404. that's because the root is https://4dmodeller.github.io/fdmr
 the root domain should redirect to the home page.

**Comment by gareth-j** [comment]
Create a redirect html page.

**Comment by gareth-j** [comment]
Done with https://github.com/4DModeller/4DModeller.github.io/commit/18ca4ee0630d338c243bcd9309dd0b1337214e6d
